CREATE TABLE `task` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`username` CHAR(255) NOT NULL DEFAULT '',
	`email` CHAR(255) NOT NULL DEFAULT '',
	`text` TEXT NOT NULL,
	`status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
